/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package schemas.weather;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class wind extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -153120657520693412L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"wind\",\"namespace\":\"schemas.weather\",\"fields\":[{\"name\":\"deg\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"speed\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<wind> ENCODER =
      new BinaryMessageEncoder<wind>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<wind> DECODER =
      new BinaryMessageDecoder<wind>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<wind> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<wind> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<wind> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<wind>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this wind to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a wind from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a wind instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static wind fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Integer deg;
   private float speed;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public wind() {}

  /**
   * All-args constructor.
   * @param deg The new value for deg
   * @param speed The new value for speed
   */
  public wind(java.lang.Integer deg, java.lang.Float speed) {
    this.deg = deg;
    this.speed = speed;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deg;
    case 1: return speed;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deg = (java.lang.Integer)value$; break;
    case 1: speed = (java.lang.Float)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'deg' field.
   * @return The value of the 'deg' field.
   */
  public java.lang.Integer getDeg() {
    return deg;
  }


  /**
   * Sets the value of the 'deg' field.
   * @param value the value to set.
   */
  public void setDeg(java.lang.Integer value) {
    this.deg = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return The value of the 'speed' field.
   */
  public float getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * @param value the value to set.
   */
  public void setSpeed(float value) {
    this.speed = value;
  }

  /**
   * Creates a new wind RecordBuilder.
   * @return A new wind RecordBuilder
   */
  public static schemas.weather.wind.Builder newBuilder() {
    return new schemas.weather.wind.Builder();
  }

  /**
   * Creates a new wind RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new wind RecordBuilder
   */
  public static schemas.weather.wind.Builder newBuilder(schemas.weather.wind.Builder other) {
    if (other == null) {
      return new schemas.weather.wind.Builder();
    } else {
      return new schemas.weather.wind.Builder(other);
    }
  }

  /**
   * Creates a new wind RecordBuilder by copying an existing wind instance.
   * @param other The existing instance to copy.
   * @return A new wind RecordBuilder
   */
  public static schemas.weather.wind.Builder newBuilder(schemas.weather.wind other) {
    if (other == null) {
      return new schemas.weather.wind.Builder();
    } else {
      return new schemas.weather.wind.Builder(other);
    }
  }

  /**
   * RecordBuilder for wind instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<wind>
    implements org.apache.avro.data.RecordBuilder<wind> {

    private java.lang.Integer deg;
    private float speed;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(schemas.weather.wind.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deg)) {
        this.deg = data().deepCopy(fields()[0].schema(), other.deg);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.speed)) {
        this.speed = data().deepCopy(fields()[1].schema(), other.speed);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing wind instance
     * @param other The existing instance to copy.
     */
    private Builder(schemas.weather.wind other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.deg)) {
        this.deg = data().deepCopy(fields()[0].schema(), other.deg);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.speed)) {
        this.speed = data().deepCopy(fields()[1].schema(), other.speed);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'deg' field.
      * @return The value.
      */
    public java.lang.Integer getDeg() {
      return deg;
    }


    /**
      * Sets the value of the 'deg' field.
      * @param value The value of 'deg'.
      * @return This builder.
      */
    public schemas.weather.wind.Builder setDeg(java.lang.Integer value) {
      validate(fields()[0], value);
      this.deg = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deg' field has been set.
      * @return True if the 'deg' field has been set, false otherwise.
      */
    public boolean hasDeg() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deg' field.
      * @return This builder.
      */
    public schemas.weather.wind.Builder clearDeg() {
      deg = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * @return The value.
      */
    public float getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public schemas.weather.wind.Builder setSpeed(float value) {
      validate(fields()[1], value);
      this.speed = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'speed' field.
      * @return This builder.
      */
    public schemas.weather.wind.Builder clearSpeed() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public wind build() {
      try {
        wind record = new wind();
        record.deg = fieldSetFlags()[0] ? this.deg : (java.lang.Integer) defaultValue(fields()[0]);
        record.speed = fieldSetFlags()[1] ? this.speed : (java.lang.Float) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<wind>
    WRITER$ = (org.apache.avro.io.DatumWriter<wind>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<wind>
    READER$ = (org.apache.avro.io.DatumReader<wind>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.deg == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.deg);
    }

    out.writeFloat(this.speed);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.deg = null;
      } else {
        this.deg = in.readInt();
      }

      this.speed = in.readFloat();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.deg = null;
          } else {
            this.deg = in.readInt();
          }
          break;

        case 1:
          this.speed = in.readFloat();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










